version: '3.7'
services:
  db:
    image: mariadb:10.6.8
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
    ports:
      - 3306:3306
  redis:
    image: redis:5-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  api:
    build: .
    command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 123123
      DB_PORT: 3306
      DB_NAME: application_db
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREAD: 5
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
volumes:
  db_data:
  redis: